/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSchoolTypeRouteImport } from './routes/admin.school-type'
import { Route as AdminMapRouteImport } from './routes/admin.map'
import { Route as AdminLgaRouteImport } from './routes/admin.lga'
import { Route as AdminAssignRouteImport } from './routes/admin.assign'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolTypeRoute = AdminSchoolTypeRouteImport.update({
  id: '/school-type',
  path: '/school-type',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMapRoute = AdminMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLgaRoute = AdminLgaRouteImport.update({
  id: '/lga',
  path: '/lga',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssignRoute = AdminAssignRouteImport.update({
  id: '/assign',
  path: '/assign',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assign': typeof AdminAssignRoute
  '/admin/lga': typeof AdminLgaRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/school-type': typeof AdminSchoolTypeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assign': typeof AdminAssignRoute
  '/admin/lga': typeof AdminLgaRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/school-type': typeof AdminSchoolTypeRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/data-deletion': typeof DataDeletionRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assign': typeof AdminAssignRoute
  '/admin/lga': typeof AdminLgaRoute
  '/admin/map': typeof AdminMapRoute
  '/admin/school-type': typeof AdminSchoolTypeRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cookies'
    | '/dashboard'
    | '/data-deletion'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/support'
    | '/terms'
    | '/admin/analytics'
    | '/admin/assign'
    | '/admin/lga'
    | '/admin/map'
    | '/admin/school-type'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/dashboard'
    | '/data-deletion'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/support'
    | '/terms'
    | '/admin/analytics'
    | '/admin/assign'
    | '/admin/lga'
    | '/admin/map'
    | '/admin/school-type'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cookies'
    | '/dashboard'
    | '/data-deletion'
    | '/login'
    | '/privacy'
    | '/signup'
    | '/support'
    | '/terms'
    | '/admin/analytics'
    | '/admin/assign'
    | '/admin/lga'
    | '/admin/map'
    | '/admin/school-type'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DataDeletionRoute: typeof DataDeletionRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/school-type': {
      id: '/admin/school-type'
      path: '/school-type'
      fullPath: '/admin/school-type'
      preLoaderRoute: typeof AdminSchoolTypeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/map': {
      id: '/admin/map'
      path: '/map'
      fullPath: '/admin/map'
      preLoaderRoute: typeof AdminMapRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lga': {
      id: '/admin/lga'
      path: '/lga'
      fullPath: '/admin/lga'
      preLoaderRoute: typeof AdminLgaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/assign': {
      id: '/admin/assign'
      path: '/assign'
      fullPath: '/admin/assign'
      preLoaderRoute: typeof AdminAssignRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAssignRoute: typeof AdminAssignRoute
  AdminLgaRoute: typeof AdminLgaRoute
  AdminMapRoute: typeof AdminMapRoute
  AdminSchoolTypeRoute: typeof AdminSchoolTypeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAssignRoute: AdminAssignRoute,
  AdminLgaRoute: AdminLgaRoute,
  AdminMapRoute: AdminMapRoute,
  AdminSchoolTypeRoute: AdminSchoolTypeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DataDeletionRoute: DataDeletionRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
